In [1]:
import torch
from torch import nn
from torch.nn import functional as F

Feature_Fusion_Module(
  (fc1): Linear(in_features=512, out_features=6, bias=True)
)


NameError: name 'batchsize' is not defined

In [2]:
batchsize = 8

In [3]:

def weights_init_kaiming(m):
    classname = m.__class__.__name__
    if classname.find('Linear') != -1:
        nn.init.kaiming_normal_(m.weight, a=0, mode='fan_out')
        nn.init.constant_(m.bias, 0.0)
    elif classname.find('Conv') != -1:
        nn.init.kaiming_normal_(m.weight, a=0, mode='fan_in')
        if m.bias is not None:
            nn.init.constant_(m.bias, 0.0)
    elif classname.find('BatchNorm') != -1:
        if m.affine:
            nn.init.normal_(m.weight, 1.0, 0.02)
            nn.init.constant_(m.bias, 0.0)


class Feature_Fusion_Module(nn.Module):
    # 自定义特征融合模块
    def __init__(self, ** kwargs):
        super(Feature_Fusion_Module, self).__init__()
        # Classifier for each stripe
        self.fc1 = nn.Linear(512, 6)
        self.fc1.apply(weights_init_kaiming)


    def forward(self, x):
        x = torch.sigmoid(self.fc1(x))
        return x


ffm = Feature_Fusion_Module()
print(ffm)
rd = torch.randn(batchsize, 512)
print(rd.shape)
res = ffm(rd)
print(res)
print(res.shape)
print('complete check.')

Feature_Fusion_Module(
  (fc1): Linear(in_features=512, out_features=6, bias=True)
)
torch.Size([8, 512])
tensor([[2.6564e-04, 9.0955e-05, 2.1615e-02, 1.6105e-03, 9.8068e-06, 9.0712e-01],
        [9.9885e-01, 1.0000e+00, 5.5381e-02, 2.3682e-16, 7.2926e-02, 9.7148e-04],
        [1.0600e-06, 2.3232e-01, 4.6988e-13, 9.4187e-01, 5.4587e-03, 1.0000e+00],
        [9.9605e-01, 9.8943e-01, 1.1381e-05, 9.9995e-01, 2.1420e-10, 4.0579e-01],
        [1.0000e+00, 9.4973e-01, 1.0000e+00, 9.9984e-01, 6.8920e-08, 9.9995e-01],
        [4.4165e-17, 9.9347e-01, 2.7593e-02, 9.3344e-03, 2.5337e-05, 4.6086e-08],
        [9.9907e-01, 1.4795e-07, 7.7169e-01, 4.6511e-02, 3.1844e-10, 1.1207e-01],
        [9.9727e-01, 9.9571e-01, 1.0000e+00, 7.9550e-01, 1.7571e-08, 9.9780e-01]],
       grad_fn=<SigmoidBackward>)
torch.Size([8, 6])
complete check.


In [5]:
features_H = []  # contains 6 ([N, 256, 1])
for i in range(6):
    stripe_features_H = torch.randn(8,256,1)
    features_H.append(stripe_features_H)

In [16]:
mult_factor= res

In [30]:
features_res = []
print(mult_factor)
for id,feature in enumerate(features_H):
    new_feature = feature*mult_factor[:,id].view(batchsize,1,1).expand(features_H[id].shape)
    print(new_feature/feature)
    print(new_feature.shape)
    features_res.append(new_feature)

tensor([[2.6564e-04, 9.0955e-05, 2.1615e-02, 1.6105e-03, 9.8068e-06, 9.0712e-01],
        [9.9885e-01, 1.0000e+00, 5.5381e-02, 2.3682e-16, 7.2926e-02, 9.7148e-04],
        [1.0600e-06, 2.3232e-01, 4.6988e-13, 9.4187e-01, 5.4587e-03, 1.0000e+00],
        [9.9605e-01, 9.8943e-01, 1.1381e-05, 9.9995e-01, 2.1420e-10, 4.0579e-01],
        [1.0000e+00, 9.4973e-01, 1.0000e+00, 9.9984e-01, 6.8920e-08, 9.9995e-01],
        [4.4165e-17, 9.9347e-01, 2.7593e-02, 9.3344e-03, 2.5337e-05, 4.6086e-08],
        [9.9907e-01, 1.4795e-07, 7.7169e-01, 4.6511e-02, 3.1844e-10, 1.1207e-01],
        [9.9727e-01, 9.9571e-01, 1.0000e+00, 7.9550e-01, 1.7571e-08, 9.9780e-01]],
       grad_fn=<SigmoidBackward>)
tensor([[[2.6564e-04],
         [2.6564e-04],
         [2.6564e-04],
         ...,
         [2.6564e-04],
         [2.6564e-04],
         [2.6564e-04]],

        [[9.9885e-01],
         [9.9885e-01],
         [9.9885e-01],
         ...,
         [9.9885e-01],
         [9.9885e-01],
         [9.9885e-01]],

 

In [27]:
features_H.shape

AttributeError: 'list' object has no attribute 'shape'

In [28]:
features_H[id]

tensor([[[ 1.8564],
         [ 0.4382],
         [ 0.8485],
         ...,
         [-0.3001],
         [ 1.2031],
         [ 0.5020]],

        [[ 0.3259],
         [ 2.2329],
         [ 0.1460],
         ...,
         [ 1.9029],
         [ 0.0077],
         [-2.3000]],

        [[-1.4101],
         [ 0.3413],
         [-0.2845],
         ...,
         [-0.8871],
         [-1.3615],
         [-0.7424]],

        ...,

        [[ 0.3400],
         [-0.1131],
         [ 0.8354],
         ...,
         [ 1.2913],
         [-0.1840],
         [ 0.5769]],

        [[-0.0572],
         [ 1.6035],
         [ 1.0149],
         ...,
         [-0.1353],
         [-0.7461],
         [ 0.5826]],

        [[-2.1842],
         [ 0.7432],
         [-0.4142],
         ...,
         [-0.1917],
         [ 0.9167],
         [-1.3274]]])